trainingInput:
  pythonVersion: "3.5"
  hyperparameters:
    goal: MINIMIZE
    hyperparameterMetricTag: validation_rmse
    maxTrials: 4
    maxParallelTrials: 1
    enableTrialEarlyStopping: True
    params:

      - parameterName: offset
        type: DOUBLE
        minValue: -0.09
        maxValue: -0.19
        scaleType: UNIT_LINEAR_SCALE
