trainingInput:
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: accuracy
    maxTrials: 4
    maxParallelTrials: 2
    enableTrialEarlyStopping: True
    params:

      # CONV

      - parameterName: num_conv_layers
        type: INTEGER
        minValue: 3
        maxValue: 8
        scaleType: UNIT_LINEAR_SCALE

      - parameterName: conv1_kernel_size
        type: INTEGER # 3,5,7,12
        minValue: 0
        maxValue: 3
        scaleType: UNIT_LINEAR_SCALE


      - parameterName: conv1_filter_num
        type: INTEGER # 8,16,24,32
        minValue: 0
        maxValue: 3
        scaleType: UNIT_LINEAR_SCALE

      - parameterName: conv1_stride
        type: INTEGER # 1,2,4
        minValue: 0
        maxValue: 2
        scaleType: UNIT_LINEAR_SCALE

      - parameterName: filter_num_scale_factor
        type: DOUBLE
        minValue: 1.0
        maxValue: 2.0
        scaleType: UNIT_LOG_SCALE

      - parameterName: filter_num_scale_decay
        type: DOUBLE
        minValue: 0.0
        maxValue: 1.0
        scaleType: UNIT_LOG_SCALE

      - parameterName: num_kernal_size_decrements
        type: INTEGER
        minValue: 0
        maxValue: 2
        scaleType: UNIT_LINEAR_SCALE

      - parameterName: last_decrement_layer
        type: DOUBLE
        minValue: 0.0
        maxValue: 1.0
        scaleType: UNIT_LOG_SCALE

      # DENSE

      - parameterName: first_dense_layer_size
        type: INTEGER
        minValue: 500
        maxValue: 2000
        scaleType: UNIT_LINEAR_SCALE

      - parameterName: num_dense_layers
        type: INTEGER
        minValue: 1
        maxValue: 10
        scaleType: UNIT_LINEAR_SCALE

      - parameterName: dense_scale_factor
        type: DOUBLE
        minValue: 0.1
        maxValue: 1.0
        scaleType: UNIT_REVERSE_LOG_SCALE
